### ISSUE TITLE
[Contribution] Chrome Extension Launcher

### ISSUE THREAD

**Issue by jeremyben** [rubenspgcavalcante/webpack-chrome-extension-reloader#100]
**Type:**
- [ ] bug
- [ ] feature
- [ ] enhancement
- [ ] question
- [x] heads-up

**Description:**
Hi, thanks for your plugin. It inspired me to code a "companion" plugin, in order to have a even smoother experience developping chrome extensions.
I figured you, Rubens, and the other developpers here, would appreciate it:

**https://github.com/jeremyben/webpack-chrome-extension-launcher**

Of course, I decided to mention your plugin in my readme.
Keep up the good work !

Jeremy

**Comment by rubenspgcavalcante** [comment]
Hey Jeremy! Awesome, thanks for citing me :)
If you have any questions to apply on your plugin don't mind to ask!
Whenever you see improvements or this plugin too, PRs are very welcome too

All the best!

**Comment by jeremyben** [comment]
Thanks ! Yeah I noticed something on contentscript arrays not working for hot reload, I think I got the root cause in your code, so I might do a PR this week or next.
