### ISSUE TITLE
Disable WCER-W2, and consider supporting Firefox

### ISSUE THREAD

**Issue by mshindal** [rubenspgcavalcante/webpack-chrome-extension-reloader#102]
**Type:**
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] question

**Environment:**
 - OS: Windows 10
 - Library Version: 1.3.0

**I'm going to open a PR:**
- [ ] yes
- [x] no

**Description:**
Even though this plugin is called `webpack-chrome-extension-reloader`, it seems to work for hot reloading Firefox extensions too. The only annoyance is that I'm seeing [WCER-W2](https://github.com/rubenspgcavalcante/webpack-chrome-extension-reloader/wiki/General-Information#WCER-W2) in the logs when using it with Firefox. 

* Should we add an option to disable this warning?

* Should we consider expanding the scope of this project to include Firefox too?

**Comment by rubenspgcavalcante** [comment]
Hey @mshindal thanks for the feedback and for raising this subject.
Surely, I've been thinking for a while now on migrate it to follow the [WebExtensions API Standard](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions).

Of course, it will need some abstraction layer to support some specifics from each browser (like the case of Chrome reloading lock problem) but surely this is achievable. 
If the plugin is built following this standard, it's possible to use it for creating extensions for every modern browser. Although it needs some research and tests, I already reserved the package name and published a blank version just in case.

**Comment by mshindal** [comment]
Yeah it would be awesome if you ported it to follow the WebExtensions API!

Just so you know though, it works **right now** on Firefox, because Firefox supports a bunch of the `chrome.*` APIs. No changes needed.

**Comment by rubenspgcavalcante** [comment]
Exactly, because FF is following the *standard API*, together with the latest major browsers.
Each browser have their own namespace tho, while they're converting to be 100% standard.
I already put a blank github project/npm pckg placehold and as soon I get free time I'll dive into this.
Until there I'll see if I can work on disabling this error on non Chrome browsers :)

**Comment by rubenspgcavalcante** [comment]
Done! The first (beta) version of Webpack Extension Reloader where published on npm.
If you want to try out: https://github.com/rubenspgcavalcante/webpack-extension-reloader
