### ISSUE TITLE
Show production build in sample

### ISSUE THREAD

**Issue by ecwyne** [rubenspgcavalcante/webpack-chrome-extension-reloader#18]
@rubenspgcavalcante this project looks amazing! It appears to solve a ton of pain points I've had with developing chrome extensions. However, I have one question.

The readme says not to use this plugin for production builds, would it be possible to update the `/sample` to include an example of how to do a production build?

**Comment by rubenspgcavalcante** [comment]
Thanks @ecwyne , I'm glad to help you and the community!
Normally we can differ a production to a non-production build using the NODE_ENV variable.
So, I'll do this addition to both read-me and the plugin sample webpack config.

**Comment by rubenspgcavalcante** [comment]
Closed by #19
