### ISSUE TITLE
Problem in injected script

### ISSUE THREAD

**Issue by Taraflex** [rubenspgcavalcante/webpack-chrome-extension-reloader#23]
**Type:**
- [x] bug  
- [ ] feature
- [ ] enhancement
- [ ] question
 
**Environment:**
 - OS: N/A
 - Version: 0.6.1 
 
**Going to open a PR:**
- [ ] yes
- [x] no
 
**Description:**  

Double quotes must be single quotes or back-tick
https://github.com/rubenspgcavalcante/webpack-chrome-extension-reloader/blob/master/src/middleware/wcer-middleware.ts#L8-L9
Variables signals and config already contains double quotes.
Or add escaping in template variables.

**Comment by rubenspgcavalcante** [comment]
The messages aren't showing on the console

**Comment by rubenspgcavalcante** [comment]
This is caused because of prettier (added in the v0.6.1).
Going to fix that.
