### ISSUE TITLE
Add guide to how to test with the sample extension

### ISSUE THREAD

**Issue by hanzichi** [rubenspgcavalcante/webpack-chrome-extension-reloader#47]
I wonder if there is a simple demo extension for the plugin? thanks

**Comment by rubenspgcavalcante** [comment]
Yes, you can find it [here](https://github.com/rubenspgcavalcante/webpack-chrome-extension-reloader/tree/master/sample).
Although it needs a better docs :)

**Comment by acfasj** [comment]
@rubenspgcavalcante in npm scripts, `NODE_ENV=production` not work in windows. Would you like to support it across platforms by `cross-env` ?

**Comment by rubenspgcavalcante** [comment]
@acfasj I think you can simply use `cross-env` directly with npx
Never tested tho 🤔
