### ISSUE TITLE
Babel 7 Support

### ISSUE THREAD

**Issue by zsherman** [rubenspgcavalcante/webpack-chrome-extension-reloader#56]
**Type:**
- [x] bug

**Environment:**
 - OS: Mac
 - Library Version: `0.8.3`

**I'm going to open a PR:**
- [x] maybe

**Description:**

Just a report that the extension reloader appears to have issues with babel 7, I've used it successfully before on a previous version but after upgrading it seems very inconsistent. Noticed this while running the example provided in the sample folder.

**Comment by rubenspgcavalcante** [comment]
Hi @zsherman , thanks for the info.
Sorry about the late response (changing from company, not enough time to work on my projects)

Whenever I get some time I'll work on that :)
