### ISSUE TITLE
console info undefined reloading not working

### ISSUE THREAD

**Issue by yss14** [rubenspgcavalcante/webpack-chrome-extension-reloader#63]
**Type:**
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] question

**Environment:**
 - OS: Mac OS X
 - Library Version: 1.0.0 (webpack 4.26.0, webpack-cli 3.1.2)

**I'm going to open a PR:**
- [ ] yes
- [x] no

**Description:**

When using this plugin, a `undefined` log appears when opening a webpage on which the plugin is running.
Here's my config:
```javascript
const CopyWebpackPlugin = require('copy-webpack-plugin');
const ChromeExtensionReloader = require('webpack-chrome-extension-reloader');

const babelLoader = {
	loader: 'babel-loader',
	options: {
		cacheDirectory: true,
		presets: [
			"react",
			[
				"es2015",
				{
					"modules": false
				}
			],
			"es2016"
		]
	}
};

module.exports = {
	cache: true,
	entry: {
		'content-script': ["./src/index.tsx"]
	},
	mode: 'development',
	output: {
		path: __dirname + '/dist',
		filename: '[name].js'
	},
	devtool: "source-map",
	resolve: {
		extensions: [".ts", ".tsx", ".js"]
	},
	module: {
		rules: [
			{
				test: /\.ts(x?)$/,
				exclude: /node_modules/,
				use: [
					babelLoader,
					{
						loader: 'ts-loader'
					}
				]
			},
			{
				test: /\.js$/,
				exclude: /node_modules/,
				use: [
					babelLoader
				]
			}
		],
	},

	plugins: [
		new CopyWebpackPlugin([
			{
				from: "./node_modules/react/umd/react.development.js",
				to: ""
			},
			{
				from: "./node_modules/react-dom/umd/react-dom.development.js",
				to: ""
			},
			{
				from: "./node_modules/babel-polyfill/dist/polyfill.min.js",
				to: ""
			}
		]),
		new ChromeExtensionReloader({
			port: 9090, // Which port use to create the server
			reloadPage: true, // Force the reload of the page also
			entries: { //The entries used for the content/background scripts
				contentScript: 'content-script', //Use the entry names, not the file name or the path
			}
		})
	],
	performance: {
		hints: false
	},
	externals: {
		"react": "React",
		"react-dom": "ReactDOM"
	},
};
```

Here is the log:
![screen shot 2018-12-11 at 13 59 42](https://user-images.githubusercontent.com/4346842/49802413-22071a00-fd4d-11e8-8826-e958367745ac.png)
![screen shot 2018-12-11 at 13 59 55](https://user-images.githubusercontent.com/4346842/49802414-22071a00-fd4d-11e8-9d75-10fc04ead208.png)

**Comment by rubenspgcavalcante** [comment]
Humm, it seems that the connection signal is coming with an empty payload.
It should be showing `[ WCER: Connected to Chrome Extension Hot Reloader ]`
I'll try to reproduce with a similar setup as yours (without any background script)

**Comment by jeromewir** [comment]
I can confirm the bug happens when no background script is specified
https://github.com/rubenspgcavalcante/webpack-chrome-extension-reloader/blob/c7c590da5098263010e29e7d7bb13995f1333765/src/middleware/wcer-middleware.ts#L47-L97 never gets called and therefore, the message in never catch

Adding background to my `manifest.json` with an empty file fixed the problem 👍 
```
"background": {
    "scripts": ["background.js"],
    "persistent": false
}
```

**Comment by rubenspgcavalcante** [comment]
Awesome @jeromewir , thanks for the info! :D
I'll work on the background script checking 👍

**Comment by rubenspgcavalcante** [comment]
Releasing a patch version for that 👍

**Comment by yss14** [comment]
Thanks for that clarification! Will try it out :)
