### ISSUE TITLE
Verify if mode === "development" to activate the hot-reloading

### ISSUE THREAD

**Issue by lonyele** [rubenspgcavalcante/webpack-chrome-extension-reloader#68]
**Type:**
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] question

**Environment:**
 - OS: Windows 10 pro
 - Library Version: 1.0.1

**I'm going to open a PR:**
- [x] yes
- [ ] no

**Description:**
Hi, I've used the library around march and It worked fine at that time. I'm trying to build a fresh new chrome extension project and It seems like hot reloading is not working now.  I've tested with both my local setting, and the sample project on this github repo. 
  As I remember when content-script or event-script is injected or running, it should spit out something like `[ WCER: Connected to Chrome Extension Hot Reloader ]`, but I don't get any of this library's console output.  maybe wcer-middleware is not injected or... something went wrong. 
hm... I think it is somewhat working for popup and option page. after save some code, webpack rebuilds. I refresh option page or click popup again, code is updated. However event-script and content-script need chrome extension to be manually reloaded

I just tested with this repo's sample project and here is my local setting of manifest and webpack.config.js for more information
```
{
  "manifest_version": 2,
  "name": "testCXdevEnv",
  "description": "chrome extension dev setting",
  "version": "1.0",
  "background": {
    "scripts": ["event.bundle.js"],
    "persistent": false
  },
  "browser_action": {
    "default_title": "CX devEnv!",
    "default_popup": "popup.html"
  },
  "content_scripts": [
    {
      "matches": ["*://*/*"],
      "js": ["content.bundle.js"]
    }
  ],
  "permissions": [
    "activeTab",
    "http://*/*",
    "https://*/*",
    "tabs",
    "storage",
    "sessions"
  ],
  "web_accessible_resources": ["injectedIframe1.html", "injectedIframe2.html"],
  "content_security_policy": "script-src 'self' http://localhost:*/ 'unsafe-eval'; object-src 'self'"
}

```
```
const path = require("path");
const webpack = require("webpack");
const ChromeExtensionReloader = require("webpack-chrome-extension-reloader");

module.exports = {
  context: path.resolve(__dirname, "./src"),
  entry: {
    event: "./event.ts",
    content: "./content.js",
    popup: "./popup.tsx",
    option: "./option.tsx",
    injectedIframe1: "./injectedIframe1.js",
    injectedIframe2: "./injectedIframe2.js"
  },
  output: {
    path: path.resolve(__dirname, "./dist"),
    filename: "[name].bundle.js"
  },
  resolve: {
    extensions: [".ts", ".tsx", ".js"]
  },
  module: {
    rules: [
      {
        test: /\.(ts||tsx)$/,
        enforce: "pre",
        loader: "tslint-loader"
      },
      {
        test: /\.(js||ts||tsx)$/,
        use: "ts-loader",
        exclude: /node_modules/
      }
    ]
  },
  plugins: [
    new ChromeExtensionReloader({
      port: 9090, // Which port use to create the server
      reloadPage: true, // Force the reload of the page also
      entries: {
        //The entries used for the content/background scripts
        contentScript: "content", //Use the entry names, not the file name or the path
        background: "event",
        popup: "popup"
      }
    })
  ]
};
```

**Comment by rubenspgcavalcante** [comment]
Hey @lonyele , thanks for the feedback.
Interesting, locally seems to be fine, so I'll need to do more tests based on your setup. Can you provide  your sample, only if possible of course (you can erase the actual app and give me a "blank" version, just need the environment), if isn't possible I can try to mount a similar setup.
Can you also test with an older version, other than 1.0.1, to see if works ok like you said it worked a while ago.

**Comment by herteleo** [comment]
Hi @rubenspgcavalcante,
> Can you also test with an older version, other than 1.0.1

With 1.0.1 I have the same problem as described by @lonyele. I tried version 1.0.0 and now it works for me.

**Comment by lonyele** [comment]
I think I found what causes this problem. I downgraded to v1.0.0. and it works. If I run with v1.0.1, I get 
```
$ webpack --mode=development --watch
undefined

webpack is watching the files…
...and so on
```

I found that the `undefined` console output is from `console.log(NODE_ENV)`(`ChromeExtensionReloader.ts`). It is a problem of NODE_ENV. 

It don't know If I'm right but I found that with v1.0.0 ` webpack --mode=development --watch` works but not in the v1.0.1.  Just for a quick fix, I could run succefully with `SET NODE_ENV=develpoment& webpack --mode=development --watch`  (SET NODE_ENV=development because I'm on Windows)

I couldn't find where but this code from `ChromeExtensionReloader.ts` of v1.0.0 
```
...
apply(compiler: any) {
    this._eventAPI = new CompilerEventsFacade(compiler);
    console.log("??")
    if (process.env.NODE_ENV === "development") {  
      this._eventAPI.afterOptimizeChunkAssets(
        (comp, chunks) =>{
          (comp.assets = {
            ...comp.assets,
            ...this._injector(comp.assets, chunks)
          })
        }
      );

      this._eventAPI.afterEmit((comp, done) =>
        this._triggerer()
          .then(done)
          .catch(done)
      );
    }
    else {
      console.warn("Chrome Extension Reloader Plugin runs only on NODE_ENV=development");
    }
  }
```
`if (process.env.NODE_ENV === "development") {  `  ---> this part always become `true` on v1.0.0.  I couldn't find where it set the NODE_ENV internally. on v1.0.1  this `process.env.NODE_ENV` is undefined unless explicitly configured on webpack `SET NODE_ENV=develpoment& webpack --mode=development --watch`
 
 With this webpack command `webpack --mode=development --watch` 
On v1.0.0 `console.log(process.env.NODE_ENV)` is a `development`
But on v1.0.1 `console.log(process.env.NODE_ENV)` is a `undefined`

I'm not sure whether this problem is from util/env.js or somewhere between from v1.0.0 to v1.0.1  or from webpack. My guess is from things added from v1.0.0 has the problem. 

Maybe this can be a help [NODE_ENV not set on process.env]( https://github.com/webpack/webpack/issues/7074)

**Comment by rubenspgcavalcante** [comment]
Ah got it. Actually was a fixed introduced on the v1.0.1.
Typescript was parsing by default all the NODE_ENV === "production" to preset values to `true` on the final bundle, considering my environment as base. Then I fixed that to consider the NODE_ENV of who is using the plugin.
The reason that this is very important is to avoid, when env is "production", the inclusion of the plugin code (the middleware) on the final bundle, unnecessarily bloating the extension.
Although it was supposed to be throwing a warning message, saying that the hot-reload-server will only work when `NODE_ENV=development`.

I'll make a fix to consider the `mode` set to the webpack config, and not the NODE_ENV, and make sure the warn appears on the console whenever the `mode === "production"` and the plugin was included.

**Comment by lonyele** [comment]
Thanks for your support (btw I thought setting webpack mode automatically sets NODE_ENV, but that's not the case...)

**Comment by rubenspgcavalcante** [comment]
After merging, I'll promptly release a PATCH version (v1.0.2)
Thanks for all the information :D
