### ISSUE TITLE
reload devtools_page

### ISSUE THREAD

**Issue by mixtur** [rubenspgcavalcante/webpack-chrome-extension-reloader#7]
Given this code
```js
// manifest.json
...
"devtools_page": "devtools.html",
...

// devtools.html
<script src="j/devtool.js"></script>

// devtool.js
chrome.devtools.panels.create('abc', '', 'devpanel.html', function() {});

// devpanel.html
<script src="j/devpanel.js"></script>

```

Is it possible to reload `devtool.js` and `devpanel.js`?

I could install some instrumentation manually if that is the problem.

**Comment by rubenspgcavalcante** [comment]
Currently the plugin reloads all the assets managed by the webpack.
If both devpanel and devtool are processed and outputted by Webpack, it should work. You still need to have both content and background scripts for this plugin work tho.

**Comment by mixtur** [comment]
All javascript files are managed by webpack indeed. Yet content script is reloaded, background script is reloaded, and devtools/devpanel for some reason is not. Maybe there is some exception thrown that I cannot see because there is no devtools for devtools) I'll try to dig deeper at some point later.
