### ISSUE TITLE
How to prevent popup tab from closing?

### ISSUE THREAD

**Issue by OriginalEXE** [rubenspgcavalcante/webpack-chrome-extension-reloader#70]
**Type:**
- [ ] bug
- [ ] feature
- [ ] enhancement
- [x] question

**Environment:**
 - OS: Ubuntu 18.04
 - Library Version: 1.1.1

**I'm going to open a PR:**
- [ ] yes
- [x] no

**Description:**
Hello!

First of all, thank you for maintaining this useful library. I have one issue that prevents me from using it, and I wanted to check whether it is possible to accommodate my use case.

When I am developing a view inside the popup, I like having it always visible (instead of having to click on the icon to show it each time). I do that by inspecting the network request of the popup, and simply opening the main one in the new tab. It works great. The problem is, once I use your library, once a change is performed the popup tab closes, and then I have to open it again. Ideally, it would just refresh.

Do you think this is doable? I believe it would be useful to many, but maybe I am wrong and there is a better way to develop popup views, in which case, please educate me :)

Thanks,
Ante

**Comment by OriginalEXE** [comment]
Hey @rubenspgcavalcante 

Than's for getting back to me. I have already tried setting the option to false before reaching out, but I saw no difference in the behavior unfortunately.

**Comment by OriginalEXE** [comment]
Thanks a lot. I am totally fine with reloading it manually, that's what I am doing without the plugin anyways, but I do want to take advantage of other benefits of this library, so just having the popup not close would be awesome.

**Comment by Joaquin6** [comment]
> Thanks a lot. I am totally fine with reloading it manually, that's what I am doing without the plugin anyways, but I do want to take advantage of other benefits of this library, so just having the popup not close would be awesome.

any updates here?

**Comment by rubenspgcavalcante** [comment]
Sorry, took a long vacation and was only able to work on this now.
Now the plugin is taking a more smart strategy, only reloads the chrome extension when is necessary, when content or background scripts (or anything in their dependency tree) are emitted by webpack.

This makes the popup maintain itself open after webpack emits any other files or entries then content or background entries.

Hope this sounds good :)
