### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by acc15** [rubenspgcavalcante/webpack-chrome-extension-reloader#78]
**Type:**
- [ ] bug
- [X] feature
- [ ] enhancement
- [ ] question

**Environment:**
 - OS:any
 - Library Version: any

**I'm going to open a PR:**
- [ ] yes
- [X] no

**Description:**
`typings/index.d.ts` doesn't contains any typeinfo about options, etc.

Please add support for typescript webpack configuration.

**Comment by acc15** [comment]
Thank you!!!

but

```typescript
declare module "webpack-chrome-extension-reloader" {
  type PluginOptions = {
    port: number;
    reloadPage: boolean;
    entries: EntriesOption;
  };
  type EntriesOption = {
    background: string;
    contentScript: ContentScriptOption;
  };

  type ContentScriptOption = string | Array<string>;

  interface ChromeExtensionReloaderConstructor {
    new (options?: PluginOptions): ChromeExtensionReloader;
  }

  export default interface ChromeExtensionReloader {
    apply(compiler: Object): void;
  }
}
```

I think that `ChromeExtensionReloaderConstructor`  must be in default export. If usage is:

```javascript
    new ChromeExtensionReloader({
      entries: { 
        contentScript: ['my-first-content-script', 'my-second-content-script', /* and so on ... */],
        background: 'background'
      }
    })
```

Currently `ChromeExtensionReloader` is useless

**Comment by orokanasaru** [comment]
@rubenspgcavalcante,

As @acc15 says, the definitions provided here are unusable since `ChromeExtensionReloader` doesn't have a constructor.

**Comment by acc15** [comment]
#83

**Comment by rubenspgcavalcante** [comment]
Hey people, sorry for the late response (I was on vacations).
That's true, will patch this :D
