### ISSUE TITLE
Fix Typescript definitions

### ISSUE THREAD

**Issue by acc15** [rubenspgcavalcante/webpack-chrome-extension-reloader#83]
**Type:**
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] question

**Environment:**
 - OS: any
 - Library Version: 1.2.0

**I'm going to open a PR:**
- [ ] yes
- [x] no

**Description:**
Typescript definitions are broken. See #78

**Comment by rubenspgcavalcante** [comment]
Closing this one in favor of #78 (all the info is there) 👍
